services:
  - type: web
    name: subtitleeditor-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
